config/routes.rb
Sunshine::Application.routes.draw do
  resources :voters

  devise_for :users

  resources :volunteers
  root to: 'volunteers#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :user_name, :username,
                  :address, :county, :phone, :hours, :account_type,
                  :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  def full_name
    first_name + " " + last_name
  end

end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  attr_accessible :address, :county, :email, :hours, :name, :phone
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  attr_accessible :address, :assigned_volunteer, :confirmed_vote, :county, :email, :name, :party_affiliation, :phone

  def assigned_volunteer
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  # GET /volunteers
  # GET /volunteers.json
  def index
    @volunteers = Volunteer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @volunteers }
    end
  end

  # GET /volunteers/1
  # GET /volunteers/1.json
  def show
    @volunteer = Volunteer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @volunteer }
    end
  end

  # GET /volunteers/new
  # GET /volunteers/new.json
  def new
    @volunteer = Volunteer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @volunteer }
    end
  end

  # GET /volunteers/1/edit
  def edit
    @volunteer = Volunteer.find(params[:id])
  end

  # POST /volunteers
  # POST /volunteers.json
  def create
    @volunteer = Volunteer.new(params[:volunteer])

    respond_to do |format|
      if @volunteer.save
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully created.' }
        format.json { render json: @volunteer, status: :created, location: @volunteer }
      else
        format.html { render action: "new" }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /volunteers/1
  # PUT /volunteers/1.json
  def update
    @volunteer = Volunteer.find(params[:id])

    respond_to do |format|
      if @volunteer.update_attributes(params[:volunteer])
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1
  # DELETE /volunteers/1.json
  def destroy
    @volunteer = Volunteer.find(params[:id])
    @volunteer.destroy

    respond_to do |format|
      format.html { redirect_to volunteers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  # GET /voters
  # GET /voters.json
  def index
    @voters = Voter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @voters }
    end
  end

  # GET /voters/1
  # GET /voters/1.json
  def show
    @voter = Voter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @voter }
    end
  end

  # GET /voters/new
  # GET /voters/new.json
  def new
    @voter = Voter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @voter }
    end
  end

  # GET /voters/1/edit
  def edit
    @voter = Voter.find(params[:id])
  end

  # POST /voters
  # POST /voters.json
  def create
    @voter = Voter.new(params[:voter])

    respond_to do |format|
      if @voter.save
        format.html { redirect_to @voter, notice: 'Voter was successfully created.' }
        format.json { render json: @voter, status: :created, location: @voter }
      else
        format.html { render action: "new" }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /voters/1
  # PUT /voters/1.json
  def update
    @voter = Voter.find(params[:id])

    respond_to do |format|
      if @voter.update_attributes(params[:voter])
        format.html { redirect_to @voter, notice: 'Voter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voters/1
  # DELETE /voters/1.json
  def destroy
    @voter = Voter.find(params[:id])
    @voter.destroy

    respond_to do |format|
      format.html { redirect_to voters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sunshine</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a href="#" class="brand">Sunshine</a>
				<ul class="nav">
					<li><%= link_to "Volunteers", volunteers_path %></li>
          <li><%= link_to "Voters", voters_path %></li>
			</div>
		</div>
	</div>
	<div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
		
    <%= yield %>

</body>
</html>

app/views/volunteers/_form.html.erb
<%= simple_form_for(@volunteer, html: {class: "form-horizontal"}) do |f| %>
  <% if @volunteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@volunteer.errors.count, "error") %> prohibited this volunteer from being saved:</h2>

      <ul>
      <% @volunteer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :name %><br />
  </div>
  <div class="field">
    <%= f.input :address %><br />
  </div>
  <div class="field">
    <%= f.input :county %><br />
  </div>
  <div class="field">
    <%= f.input :phone %><br />
  </div>
  <div class="field">
    <%= f.input :email %><br />
  </div>
  <div class="field">
    <%= f.input :hours %><br />
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/volunteers/edit.html.erb
<h1>Editing volunteer</h1>

<%= render 'form' %>

<%= link_to 'Show', @volunteer %> |
<%= link_to 'Back', volunteers_path %>

app/views/volunteers/index.html.erb
<div class="page-header">
    <h1>All Volunteers</h1>
</div>

<div class="btn btn-success">
    <%= link_to "Create a New Volunteer", new_volunteer_path %>
</div>

<% @volunteers.each do |volunteer| %>
<div class="volunteer">
    <strong><u><%= volunteer.name %></u></strong>
    <p><strong>Address: </strong><%= volunteer.address %></p>
    <p><strong>County: </strong><%= volunteer.county %></p>
    <p><strong>Phone: </strong><%= volunteer.phone %></p>
    <p><strong>Email: </strong><%= volunteer.email %></p>
    <p><strong>Availability: </strong><%= volunteer.hours + " hours" %></p>
    <div class="meta">
        <em>Entry created: <%= time_tag(volunteer.created_at) %></em>
        <span class="admin">
            | <%= link_to "Edit", edit_volunteer_path(volunteer) %> |
            <%= link_to "Delete", volunteer, method: :delete, data: { confirm: "Don't you dare!"} %>
            | <%= link_to "Assign voters"%>
        </span>
    </div>
</div>
<% end %>

app/views/volunteers/new.html.erb
<h1>New volunteer</h1>

<%= render 'form' %>

<%= link_to 'Back', volunteers_path %>

app/views/volunteers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @volunteer.name %>
</p>

<p>
  <b>Address:</b>
  <%= @volunteer.address %>
</p>

<p>
  <b>County:</b>
  <%= @volunteer.county %>
</p>

<p>
  <b>Phone:</b>
  <%= @volunteer.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @volunteer.email %>
</p>

<p>
  <b>Hours:</b>
  <%= @volunteer.hours %>
</p>


<%= link_to 'Edit', edit_volunteer_path(@volunteer) %> |
<%= link_to 'Back', volunteers_path %>

app/views/voters/_form.html.erb
<%= simple_form_for(@voter, html: {class: "form-horizontal"}) do |f| %>
  <% if @voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
      <% @volunteer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.input :name %><br />
  </div>
  <div class="field">
    <%= f.input :address %><br />
  </div>
  <div class="field">
    <%= f.input :county %><br />
  </div>
  <div class="field">
    <%= f.input :phone %><br />
  </div>
  <div class="field">
    <%= f.input :email %><br />
  </div>
  <div class="field">
    <%= f.input :party_affiliation %><br />
  </div>
  <div class="field">
    <%= f.input :confirmed_vote %><br />
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/voters/edit.html.erb
<h1>Editing voter</h1>

<%= render 'form' %>

<%= link_to 'Show', @voter %> |
<%= link_to 'Back', voters_path %>

app/views/voters/index.html.erb
<div class="page-header">
    <h1>Voter Roll</h1>
</div>

<div class="btn btn-success">
    <%= link_to "Enter New Voter Record", new_voter_path %>
</div>

<% @voters.each do |voter| %>
<div class="voter">
    <strong><u><%= voter.name %></u></strong>
    <p><strong>Address: </strong><%= voter.address %></p>
    <p><strong>County: </strong><%= voter.county %></p>
    <p><strong>Phone: </strong><%= voter.phone %></p>
    <p><strong>Email: </strong><%= voter.email %></p>
    <p><strong>Party Affiliation: </strong><%= voter.party_affiliation %></p>
    <p><strong>Confirmed Vote: </strong><%= voter.confirmed_vote %></p>
    <div class="meta">
        <em>Entry created: <%= time_tag(voter.created_at) %></em>
        <span class="admin">
            | <%= link_to "Edit", edit_voter_path(voter) %> |
            <%= link_to "Delete", voter, method: :delete, data: { confirm: "Don't you dare!"} %>
            | <%= link_to "Assign volunteers"%>
        </span>
    </div>
</div>
<% end %>

app/views/voters/new.html.erb
<h1>New voter</h1>

<%= render 'form' %>

<%= link_to 'Back', voters_path %>

app/views/voters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @voter.name %>
</p>

<p>
  <b>Address:</b>
  <%= @voter.address %>
</p>

<p>
  <b>County:</b>
  <%= @voter.county %>
</p>

<p>
  <b>Phone:</b>
  <%= @voter.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @voter.email %>
</p>

<p>
  <b>Party affiliation:</b>
  <%= @voter.party_affiliation %>
</p>

<p>
  <b>Confirmed vote:</b>
  <%= @voter.confirmed_vote %>
</p>


<%= link_to 'Edit', edit_voter_path(@voter) %> |
<%= link_to 'Back', voters_path %>